FROM hiperlife/hiperlife

# -----------------------------------------
# Configure user and work environment
# -----------------------------------------
USER hl-user
WORKDIR /home/hl-user

# -------------------------------------------------------------------
# Clone the project if it does not exist
# The '|| true' operator prevents execution from failing if it already exists
# -------------------------------------------------------------------
RUN mkdir -p hl-src && cd hl-src && \
    git clone --branch dev https://gitlab.com/hiperlife/hl-base-project.git || true && \
    cd hl-base-project && git pull

# -----------------------------------------
# Configure environment variables and folders
# -----------------------------------------
ENV HL_BASE_PATH=/home/hl-user/hl-bin
RUN mkdir -p /home/hl-user/bin

# Add the binaries directory to the PATH
ENV PATH="${PATH}:/home/hl-user/bin"

# -------------------------------------------------------------------
# Include the initialization script in the container
# These scripts will run during runtime.
# -------------------------------------------------------------------
COPY initHL.sh /home/hl-user/bin/initHL.sh
COPY detect-compiler.sh /home/hl-user/bin/detect-compiler.sh

# Switch to root to grant permissions and add necessary tools
USER root
RUN chmod +x /home/hl-user/bin/initHL.sh /home/hl-user/bin/detect-compiler.sh
RUN apt-get update && apt-get install -y gdb

# Return to the work user
USER hl-user

# -----------------------------------------
# Default working directory
# -----------------------------------------
WORKDIR /home/hl-user/

# -----------------------------------------
# Default container command
# -----------------------------------------
CMD ["/bin/bash"]