
services:
  hiperlife-container:
    image: darecfm/hiperlife-app:latest
    volumes:
      - ./External:/home/hl-user/External  # Volumen único para código, compilación y resultados
    environment:
      - PROJECT_NAME=${PROJECT_NAME:-hl-base-project} # personaliza el nombre del proyecto
    stdin_open: true
    tty: true
    command: >
      bash -c "
      /home/hl-user/bin/initHL.sh &&
      exec bash"
