name: hiperlife
services:
  hiperlife-container:
    image: darecfm/hiperlife-app:latest
    volumes:
      - ./External:/home/hl-user/External
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

    environment:
      # Essential project variables
      - PROJECT_NAME=${PROJECT_NAME:-Prove0001}
      - DEBUG_MODE=${DEBUG_MODE:-1}
      - NUM_THREADS=${NUM_THREADS:--1}
      
      # CMake build variables
      - ENABLE_TESTS=${ENABLE_TESTS:-1}
      - ENABLE_EXAMPLES=${ENABLE_EXAMPLES:-1}
      - CMAKE_FLAGS=${CMAKE_FLAGS:-}
      
      # Path variables
      - BUILD_DIR=/home/hl-user/External/${PROJECT_NAME}/build
      - SOURCE_DIR=/home/hl-user/External/${PROJECT_NAME}
      - INSTALL_PREFIX=/home/hl-user/External/hl-bin
      - HL_BASE_PATH=/home/hl-user/hl-bin
      
      # Compiler settings
      - C_COMPILER=${C_COMPILER}
      - CXX_COMPILER=${CXX_COMPILER}
    stdin_open: true
    tty: true
    command: >
      bash -c "
      /home/hl-user/bin/initHL.sh &&
      exec bash"

      
